# Generated by Django 4.2.5 on 2023-10-07 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp3', '0002_contactlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
