# Generated by Django 3.2.21 on 2023-10-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp3', '0003_delete_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlist',
            name='profession2',
            field=models.CharField(default='def', max_length=200),
            preserve_default=False,
        ),
    ]
